// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openloanResp.proto

package cn.sunline.proto;

public final class OpenloanResp {
  private OpenloanResp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface openloanRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.openloanResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string transCode = 1;</code>
     */
    java.lang.String getTransCode();
    /**
     * <code>string transCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getTransCodeBytes();

    /**
     * <code>string rcode = 2;</code>
     */
    java.lang.String getRcode();
    /**
     * <code>string rcode = 2;</code>
     */
    com.google.protobuf.ByteString
        getRcodeBytes();

    /**
     * <code>string rtime = 3;</code>
     */
    java.lang.String getRtime();
    /**
     * <code>string rtime = 3;</code>
     */
    com.google.protobuf.ByteString
        getRtimeBytes();

    /**
     * <code>string msg = 4;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 4;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>.proto.openloanResp.Robj robj = 5;</code>
     */
    boolean hasRobj();
    /**
     * <code>.proto.openloanResp.Robj robj = 5;</code>
     */
    cn.sunline.proto.OpenloanResp.openloanResp.Robj getRobj();
    /**
     * <code>.proto.openloanResp.Robj robj = 5;</code>
     */
    cn.sunline.proto.OpenloanResp.openloanResp.RobjOrBuilder getRobjOrBuilder();
  }
  /**
   * Protobuf type {@code proto.openloanResp}
   */
  public  static final class openloanResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.openloanResp)
      openloanRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use openloanResp.newBuilder() to construct.
    private openloanResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private openloanResp() {
      transCode_ = "";
      rcode_ = "";
      rtime_ = "";
      msg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private openloanResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              transCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              rcode_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              rtime_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 42: {
              cn.sunline.proto.OpenloanResp.openloanResp.Robj.Builder subBuilder = null;
              if (robj_ != null) {
                subBuilder = robj_.toBuilder();
              }
              robj_ = input.readMessage(cn.sunline.proto.OpenloanResp.openloanResp.Robj.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(robj_);
                robj_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.sunline.proto.OpenloanResp.internal_static_proto_openloanResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.sunline.proto.OpenloanResp.internal_static_proto_openloanResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.sunline.proto.OpenloanResp.openloanResp.class, cn.sunline.proto.OpenloanResp.openloanResp.Builder.class);
    }

    public interface RobjOrBuilder extends
        // @@protoc_insertion_point(interface_extends:proto.openloanResp.Robj)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string custNo = 1;</code>
       */
      java.lang.String getCustNo();
      /**
       * <code>string custNo = 1;</code>
       */
      com.google.protobuf.ByteString
          getCustNoBytes();
    }
    /**
     * Protobuf type {@code proto.openloanResp.Robj}
     */
    public  static final class Robj extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:proto.openloanResp.Robj)
        RobjOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Robj.newBuilder() to construct.
      private Robj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Robj() {
        custNo_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Robj(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                custNo_ = s;
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.sunline.proto.OpenloanResp.internal_static_proto_openloanResp_Robj_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.sunline.proto.OpenloanResp.internal_static_proto_openloanResp_Robj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.sunline.proto.OpenloanResp.openloanResp.Robj.class, cn.sunline.proto.OpenloanResp.openloanResp.Robj.Builder.class);
      }

      public static final int CUSTNO_FIELD_NUMBER = 1;
      private volatile java.lang.Object custNo_;
      /**
       * <code>string custNo = 1;</code>
       */
      public java.lang.String getCustNo() {
        java.lang.Object ref = custNo_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          custNo_ = s;
          return s;
        }
      }
      /**
       * <code>string custNo = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCustNoBytes() {
        java.lang.Object ref = custNo_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          custNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getCustNoBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, custNo_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getCustNoBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, custNo_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof cn.sunline.proto.OpenloanResp.openloanResp.Robj)) {
          return super.equals(obj);
        }
        cn.sunline.proto.OpenloanResp.openloanResp.Robj other = (cn.sunline.proto.OpenloanResp.openloanResp.Robj) obj;

        boolean result = true;
        result = result && getCustNo()
            .equals(other.getCustNo());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CUSTNO_FIELD_NUMBER;
        hash = (53 * hash) + getCustNo().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static cn.sunline.proto.OpenloanResp.openloanResp.Robj parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.sunline.proto.OpenloanResp.openloanResp.Robj parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.sunline.proto.OpenloanResp.openloanResp.Robj parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.sunline.proto.OpenloanResp.openloanResp.Robj parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.sunline.proto.OpenloanResp.openloanResp.Robj parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.sunline.proto.OpenloanResp.openloanResp.Robj parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.sunline.proto.OpenloanResp.openloanResp.Robj parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static cn.sunline.proto.OpenloanResp.openloanResp.Robj parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static cn.sunline.proto.OpenloanResp.openloanResp.Robj parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static cn.sunline.proto.OpenloanResp.openloanResp.Robj parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static cn.sunline.proto.OpenloanResp.openloanResp.Robj parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static cn.sunline.proto.OpenloanResp.openloanResp.Robj parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(cn.sunline.proto.OpenloanResp.openloanResp.Robj prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code proto.openloanResp.Robj}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:proto.openloanResp.Robj)
          cn.sunline.proto.OpenloanResp.openloanResp.RobjOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return cn.sunline.proto.OpenloanResp.internal_static_proto_openloanResp_Robj_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return cn.sunline.proto.OpenloanResp.internal_static_proto_openloanResp_Robj_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  cn.sunline.proto.OpenloanResp.openloanResp.Robj.class, cn.sunline.proto.OpenloanResp.openloanResp.Robj.Builder.class);
        }

        // Construct using cn.sunline.proto.OpenloanResp.openloanResp.Robj.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          custNo_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return cn.sunline.proto.OpenloanResp.internal_static_proto_openloanResp_Robj_descriptor;
        }

        @java.lang.Override
        public cn.sunline.proto.OpenloanResp.openloanResp.Robj getDefaultInstanceForType() {
          return cn.sunline.proto.OpenloanResp.openloanResp.Robj.getDefaultInstance();
        }

        @java.lang.Override
        public cn.sunline.proto.OpenloanResp.openloanResp.Robj build() {
          cn.sunline.proto.OpenloanResp.openloanResp.Robj result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public cn.sunline.proto.OpenloanResp.openloanResp.Robj buildPartial() {
          cn.sunline.proto.OpenloanResp.openloanResp.Robj result = new cn.sunline.proto.OpenloanResp.openloanResp.Robj(this);
          result.custNo_ = custNo_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof cn.sunline.proto.OpenloanResp.openloanResp.Robj) {
            return mergeFrom((cn.sunline.proto.OpenloanResp.openloanResp.Robj)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(cn.sunline.proto.OpenloanResp.openloanResp.Robj other) {
          if (other == cn.sunline.proto.OpenloanResp.openloanResp.Robj.getDefaultInstance()) return this;
          if (!other.getCustNo().isEmpty()) {
            custNo_ = other.custNo_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          cn.sunline.proto.OpenloanResp.openloanResp.Robj parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (cn.sunline.proto.OpenloanResp.openloanResp.Robj) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object custNo_ = "";
        /**
         * <code>string custNo = 1;</code>
         */
        public java.lang.String getCustNo() {
          java.lang.Object ref = custNo_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            custNo_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string custNo = 1;</code>
         */
        public com.google.protobuf.ByteString
            getCustNoBytes() {
          java.lang.Object ref = custNo_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            custNo_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string custNo = 1;</code>
         */
        public Builder setCustNo(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          custNo_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string custNo = 1;</code>
         */
        public Builder clearCustNo() {
          
          custNo_ = getDefaultInstance().getCustNo();
          onChanged();
          return this;
        }
        /**
         * <code>string custNo = 1;</code>
         */
        public Builder setCustNoBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          custNo_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:proto.openloanResp.Robj)
      }

      // @@protoc_insertion_point(class_scope:proto.openloanResp.Robj)
      private static final cn.sunline.proto.OpenloanResp.openloanResp.Robj DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new cn.sunline.proto.OpenloanResp.openloanResp.Robj();
      }

      public static cn.sunline.proto.OpenloanResp.openloanResp.Robj getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Robj>
          PARSER = new com.google.protobuf.AbstractParser<Robj>() {
        @java.lang.Override
        public Robj parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Robj(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Robj> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Robj> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public cn.sunline.proto.OpenloanResp.openloanResp.Robj getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int TRANSCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object transCode_;
    /**
     * <code>string transCode = 1;</code>
     */
    public java.lang.String getTransCode() {
      java.lang.Object ref = transCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transCode_ = s;
        return s;
      }
    }
    /**
     * <code>string transCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTransCodeBytes() {
      java.lang.Object ref = transCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RCODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object rcode_;
    /**
     * <code>string rcode = 2;</code>
     */
    public java.lang.String getRcode() {
      java.lang.Object ref = rcode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rcode_ = s;
        return s;
      }
    }
    /**
     * <code>string rcode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRcodeBytes() {
      java.lang.Object ref = rcode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rcode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RTIME_FIELD_NUMBER = 3;
    private volatile java.lang.Object rtime_;
    /**
     * <code>string rtime = 3;</code>
     */
    public java.lang.String getRtime() {
      java.lang.Object ref = rtime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rtime_ = s;
        return s;
      }
    }
    /**
     * <code>string rtime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRtimeBytes() {
      java.lang.Object ref = rtime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rtime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_FIELD_NUMBER = 4;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 4;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROBJ_FIELD_NUMBER = 5;
    private cn.sunline.proto.OpenloanResp.openloanResp.Robj robj_;
    /**
     * <code>.proto.openloanResp.Robj robj = 5;</code>
     */
    public boolean hasRobj() {
      return robj_ != null;
    }
    /**
     * <code>.proto.openloanResp.Robj robj = 5;</code>
     */
    public cn.sunline.proto.OpenloanResp.openloanResp.Robj getRobj() {
      return robj_ == null ? cn.sunline.proto.OpenloanResp.openloanResp.Robj.getDefaultInstance() : robj_;
    }
    /**
     * <code>.proto.openloanResp.Robj robj = 5;</code>
     */
    public cn.sunline.proto.OpenloanResp.openloanResp.RobjOrBuilder getRobjOrBuilder() {
      return getRobj();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTransCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, transCode_);
      }
      if (!getRcodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rcode_);
      }
      if (!getRtimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, rtime_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msg_);
      }
      if (robj_ != null) {
        output.writeMessage(5, getRobj());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTransCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, transCode_);
      }
      if (!getRcodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, rcode_);
      }
      if (!getRtimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, rtime_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msg_);
      }
      if (robj_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getRobj());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.sunline.proto.OpenloanResp.openloanResp)) {
        return super.equals(obj);
      }
      cn.sunline.proto.OpenloanResp.openloanResp other = (cn.sunline.proto.OpenloanResp.openloanResp) obj;

      boolean result = true;
      result = result && getTransCode()
          .equals(other.getTransCode());
      result = result && getRcode()
          .equals(other.getRcode());
      result = result && getRtime()
          .equals(other.getRtime());
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && (hasRobj() == other.hasRobj());
      if (hasRobj()) {
        result = result && getRobj()
            .equals(other.getRobj());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRANSCODE_FIELD_NUMBER;
      hash = (53 * hash) + getTransCode().hashCode();
      hash = (37 * hash) + RCODE_FIELD_NUMBER;
      hash = (53 * hash) + getRcode().hashCode();
      hash = (37 * hash) + RTIME_FIELD_NUMBER;
      hash = (53 * hash) + getRtime().hashCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      if (hasRobj()) {
        hash = (37 * hash) + ROBJ_FIELD_NUMBER;
        hash = (53 * hash) + getRobj().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.sunline.proto.OpenloanResp.openloanResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sunline.proto.OpenloanResp.openloanResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sunline.proto.OpenloanResp.openloanResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sunline.proto.OpenloanResp.openloanResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sunline.proto.OpenloanResp.openloanResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.sunline.proto.OpenloanResp.openloanResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.sunline.proto.OpenloanResp.openloanResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.sunline.proto.OpenloanResp.openloanResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.sunline.proto.OpenloanResp.openloanResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.sunline.proto.OpenloanResp.openloanResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.sunline.proto.OpenloanResp.openloanResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.sunline.proto.OpenloanResp.openloanResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.sunline.proto.OpenloanResp.openloanResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.openloanResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.openloanResp)
        cn.sunline.proto.OpenloanResp.openloanRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.sunline.proto.OpenloanResp.internal_static_proto_openloanResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.sunline.proto.OpenloanResp.internal_static_proto_openloanResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.sunline.proto.OpenloanResp.openloanResp.class, cn.sunline.proto.OpenloanResp.openloanResp.Builder.class);
      }

      // Construct using cn.sunline.proto.OpenloanResp.openloanResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        transCode_ = "";

        rcode_ = "";

        rtime_ = "";

        msg_ = "";

        if (robjBuilder_ == null) {
          robj_ = null;
        } else {
          robj_ = null;
          robjBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.sunline.proto.OpenloanResp.internal_static_proto_openloanResp_descriptor;
      }

      @java.lang.Override
      public cn.sunline.proto.OpenloanResp.openloanResp getDefaultInstanceForType() {
        return cn.sunline.proto.OpenloanResp.openloanResp.getDefaultInstance();
      }

      @java.lang.Override
      public cn.sunline.proto.OpenloanResp.openloanResp build() {
        cn.sunline.proto.OpenloanResp.openloanResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.sunline.proto.OpenloanResp.openloanResp buildPartial() {
        cn.sunline.proto.OpenloanResp.openloanResp result = new cn.sunline.proto.OpenloanResp.openloanResp(this);
        result.transCode_ = transCode_;
        result.rcode_ = rcode_;
        result.rtime_ = rtime_;
        result.msg_ = msg_;
        if (robjBuilder_ == null) {
          result.robj_ = robj_;
        } else {
          result.robj_ = robjBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.sunline.proto.OpenloanResp.openloanResp) {
          return mergeFrom((cn.sunline.proto.OpenloanResp.openloanResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.sunline.proto.OpenloanResp.openloanResp other) {
        if (other == cn.sunline.proto.OpenloanResp.openloanResp.getDefaultInstance()) return this;
        if (!other.getTransCode().isEmpty()) {
          transCode_ = other.transCode_;
          onChanged();
        }
        if (!other.getRcode().isEmpty()) {
          rcode_ = other.rcode_;
          onChanged();
        }
        if (!other.getRtime().isEmpty()) {
          rtime_ = other.rtime_;
          onChanged();
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasRobj()) {
          mergeRobj(other.getRobj());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.sunline.proto.OpenloanResp.openloanResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.sunline.proto.OpenloanResp.openloanResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object transCode_ = "";
      /**
       * <code>string transCode = 1;</code>
       */
      public java.lang.String getTransCode() {
        java.lang.Object ref = transCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          transCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string transCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTransCodeBytes() {
        java.lang.Object ref = transCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string transCode = 1;</code>
       */
      public Builder setTransCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        transCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string transCode = 1;</code>
       */
      public Builder clearTransCode() {
        
        transCode_ = getDefaultInstance().getTransCode();
        onChanged();
        return this;
      }
      /**
       * <code>string transCode = 1;</code>
       */
      public Builder setTransCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        transCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rcode_ = "";
      /**
       * <code>string rcode = 2;</code>
       */
      public java.lang.String getRcode() {
        java.lang.Object ref = rcode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rcode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rcode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRcodeBytes() {
        java.lang.Object ref = rcode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rcode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rcode = 2;</code>
       */
      public Builder setRcode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rcode = 2;</code>
       */
      public Builder clearRcode() {
        
        rcode_ = getDefaultInstance().getRcode();
        onChanged();
        return this;
      }
      /**
       * <code>string rcode = 2;</code>
       */
      public Builder setRcodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rcode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rtime_ = "";
      /**
       * <code>string rtime = 3;</code>
       */
      public java.lang.String getRtime() {
        java.lang.Object ref = rtime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rtime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rtime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRtimeBytes() {
        java.lang.Object ref = rtime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rtime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rtime = 3;</code>
       */
      public Builder setRtime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rtime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rtime = 3;</code>
       */
      public Builder clearRtime() {
        
        rtime_ = getDefaultInstance().getRtime();
        onChanged();
        return this;
      }
      /**
       * <code>string rtime = 3;</code>
       */
      public Builder setRtimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rtime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 4;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 4;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 4;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 4;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private cn.sunline.proto.OpenloanResp.openloanResp.Robj robj_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.sunline.proto.OpenloanResp.openloanResp.Robj, cn.sunline.proto.OpenloanResp.openloanResp.Robj.Builder, cn.sunline.proto.OpenloanResp.openloanResp.RobjOrBuilder> robjBuilder_;
      /**
       * <code>.proto.openloanResp.Robj robj = 5;</code>
       */
      public boolean hasRobj() {
        return robjBuilder_ != null || robj_ != null;
      }
      /**
       * <code>.proto.openloanResp.Robj robj = 5;</code>
       */
      public cn.sunline.proto.OpenloanResp.openloanResp.Robj getRobj() {
        if (robjBuilder_ == null) {
          return robj_ == null ? cn.sunline.proto.OpenloanResp.openloanResp.Robj.getDefaultInstance() : robj_;
        } else {
          return robjBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.openloanResp.Robj robj = 5;</code>
       */
      public Builder setRobj(cn.sunline.proto.OpenloanResp.openloanResp.Robj value) {
        if (robjBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          robj_ = value;
          onChanged();
        } else {
          robjBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.openloanResp.Robj robj = 5;</code>
       */
      public Builder setRobj(
          cn.sunline.proto.OpenloanResp.openloanResp.Robj.Builder builderForValue) {
        if (robjBuilder_ == null) {
          robj_ = builderForValue.build();
          onChanged();
        } else {
          robjBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.openloanResp.Robj robj = 5;</code>
       */
      public Builder mergeRobj(cn.sunline.proto.OpenloanResp.openloanResp.Robj value) {
        if (robjBuilder_ == null) {
          if (robj_ != null) {
            robj_ =
              cn.sunline.proto.OpenloanResp.openloanResp.Robj.newBuilder(robj_).mergeFrom(value).buildPartial();
          } else {
            robj_ = value;
          }
          onChanged();
        } else {
          robjBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.openloanResp.Robj robj = 5;</code>
       */
      public Builder clearRobj() {
        if (robjBuilder_ == null) {
          robj_ = null;
          onChanged();
        } else {
          robj_ = null;
          robjBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.openloanResp.Robj robj = 5;</code>
       */
      public cn.sunline.proto.OpenloanResp.openloanResp.Robj.Builder getRobjBuilder() {
        
        onChanged();
        return getRobjFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.openloanResp.Robj robj = 5;</code>
       */
      public cn.sunline.proto.OpenloanResp.openloanResp.RobjOrBuilder getRobjOrBuilder() {
        if (robjBuilder_ != null) {
          return robjBuilder_.getMessageOrBuilder();
        } else {
          return robj_ == null ?
              cn.sunline.proto.OpenloanResp.openloanResp.Robj.getDefaultInstance() : robj_;
        }
      }
      /**
       * <code>.proto.openloanResp.Robj robj = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.sunline.proto.OpenloanResp.openloanResp.Robj, cn.sunline.proto.OpenloanResp.openloanResp.Robj.Builder, cn.sunline.proto.OpenloanResp.openloanResp.RobjOrBuilder> 
          getRobjFieldBuilder() {
        if (robjBuilder_ == null) {
          robjBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.sunline.proto.OpenloanResp.openloanResp.Robj, cn.sunline.proto.OpenloanResp.openloanResp.Robj.Builder, cn.sunline.proto.OpenloanResp.openloanResp.RobjOrBuilder>(
                  getRobj(),
                  getParentForChildren(),
                  isClean());
          robj_ = null;
        }
        return robjBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.openloanResp)
    }

    // @@protoc_insertion_point(class_scope:proto.openloanResp)
    private static final cn.sunline.proto.OpenloanResp.openloanResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.sunline.proto.OpenloanResp.openloanResp();
    }

    public static cn.sunline.proto.OpenloanResp.openloanResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<openloanResp>
        PARSER = new com.google.protobuf.AbstractParser<openloanResp>() {
      @java.lang.Override
      public openloanResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new openloanResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<openloanResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<openloanResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.sunline.proto.OpenloanResp.openloanResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_openloanResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_openloanResp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_openloanResp_Robj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_openloanResp_Robj_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022openloanResp.proto\022\005proto\"\214\001\n\014openloan" +
      "Resp\022\021\n\ttransCode\030\001 \001(\t\022\r\n\005rcode\030\002 \001(\t\022\r" +
      "\n\005rtime\030\003 \001(\t\022\013\n\003msg\030\004 \001(\t\022&\n\004robj\030\005 \001(\013" +
      "2\030.proto.openloanResp.Robj\032\026\n\004Robj\022\016\n\006cu" +
      "stNo\030\001 \001(\tB\022\n\020cn.sunline.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_openloanResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_openloanResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_openloanResp_descriptor,
        new java.lang.String[] { "TransCode", "Rcode", "Rtime", "Msg", "Robj", });
    internal_static_proto_openloanResp_Robj_descriptor =
      internal_static_proto_openloanResp_descriptor.getNestedTypes().get(0);
    internal_static_proto_openloanResp_Robj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_openloanResp_Robj_descriptor,
        new java.lang.String[] { "CustNo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
